export const countryDbMap: Record<string, string> = {
  "AS-DTGBTN": "AS-DTGBTN",
  "AS-DTGGER": "AS-DTGGER",
  "AS-DTGJPN": "AS-DTGJPN",
  "AS-DTGKHM": "AS-DTGKHM",
  "AS-DTGKUL": "AS-DTGKUL",
  "AS-DTGLAO": "AS-DTGLAO",
  "AS-DTGMAL": "AS-DTGMAL",
  "AS-DTGMMR": "AS-DTGMMR",
  "AS-DTGPHL": "AS-DTGPHL",
  "AS-DTGSIN": "AS-DTGSIN",
  "AS-DTGSLK": "AS-DTGSLK",
  "AS-DTGTHA": "AS-DTGTHA",
  "AS-DTGVNM": "AS-DTGVNM",
  "Bhutan": "AS-DTGBTN",
  "Germany": "AS-DTGGER",
  "Japan": "AS-DTGJPN",
  "Cambodia": "AS-DTGKHM",
  "Malaysia": "AS-DTGKUL",
  "Laos": "AS-DTGLAO",
  "Maldives": "AS-DTGMAL",
  "Myanmar": "AS-DTGMMR",
  "Philippines": "AS-DTGPHL",
  "Singapore": "AS-DTGSIN",
  "Sri Lanka": "AS-DTGSLK",
  "Thailand": "AS-DTGTHA",
  "Vietnam": "AS-DTGVNM",
};
